# Generated by Django 5.2.5 on 2025-08-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_job_title_user_profile_img_user_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.URLField(blank=True, help_text='Cloudinary image URL', max_length=255),
        ),
    ]
