# Generated by Django 5.2.5 on 2025-08-29 11:30

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('source_language', models.CharField(max_length=50)),
                ('feedback', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(default=dict), blank=True, default=list, size=None)),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_source_texts', to='tasks.task')),
            ],
        ),
    ]
