# Generated by Django 5.2.5 on 2025-08-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source_texts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='source_file',
        ),
        migrations.AlterField(
            model_name='source',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
