# Generated by Django 5.2.5 on 2025-08-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source_texts', '0002_remove_source_source_file_alter_source_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='parent_task',
        ),
        migrations.AlterField(
            model_name='source',
            name='source_language',
            field=models.CharField(choices=[('en-gb', 'English (UK)'), ('en-us', 'English (US)'), ('fr-fr', 'French'), ('es-es', 'Spanish'), ('it-it', 'Italian'), ('de-de', 'German')], default='en-gb', max_length=25),
        ),
    ]
