# Generated by Django 5.2.5 on 2025-09-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source_texts', '0004_alter_source_source_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='body',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
