# Generated by Django 5.2.5 on 2025-09-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source_texts', '0005_alter_source_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_language',
            field=models.CharField(choices=[('en-GB', 'English (UK)'), ('en-US', 'English (US)'), ('fr-FR', 'French'), ('es-ES', 'Spanish'), ('it-IT', 'Italian'), ('gr-GR', 'Greek'), ('de-DE', 'German'), ('nl-NL', 'Dutch'), ('pl-PL', 'Polish')], default='en-GB', max_length=25),
        ),
    ]
