# Generated by Django 5.2.5 on 2025-08-30 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Termbase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_language', models.CharField(choices=[('en-GB', 'English (UK)'), ('en-US', 'English (US)'), ('fr-FR', 'French'), ('es-ES', 'Spanish'), ('it-IT', 'Italian'), ('gr-GR', 'Greek'), ('de-DE', 'German'), ('nl-NL', 'Dutch'), ('pl-PL', 'Polish')], default='en-gb', max_length=25)),
                ('target_language', models.CharField(choices=[('en-GB', 'English (UK)'), ('en-US', 'English (US)'), ('fr-FR', 'French'), ('es-ES', 'Spanish'), ('it-IT', 'Italian'), ('gr-GR', 'Greek'), ('de-DE', 'German'), ('nl-NL', 'Dutch'), ('pl-PL', 'Polish')], default='fr-FR', max_length=25)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_termbases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
