# Generated by Django 5.2.5 on 2025-08-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termbases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termbase',
            name='name',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
    ]
