# Generated by Django 5.2.5 on 2025-08-30 15:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termbases', '0002_termbase_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='termbase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='termbase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_term', models.CharField(max_length=255)),
                ('target_term', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Additional explanation of term', null=True)),
                ('termbase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='termbases.termbase')),
            ],
        ),
    ]
