# Generated by Django 5.2.5 on 2025-08-30 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source_texts', '0004_alter_source_source_language'),
        ('tasks', '0001_initial'),
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='source_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='source_texts.source'),
        ),
        migrations.AddField(
            model_name='task',
            name='translation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='translations.translation'),
        ),
    ]
