# Generated by Django 5.2.5 on 2025-08-30 08:45

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('source_texts', '0004_alter_source_source_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('target_language', models.CharField(choices=[('en-GB', 'English (UK)'), ('en-US', 'English (US)'), ('fr-FR', 'French'), ('es-ES', 'Spanish'), ('it-IT', 'Italian'), ('gr-GR', 'Greek'), ('de-DE', 'German'), ('nl-NL', 'Dutch'), ('pl-PL', 'Polish')], default='en-gb', max_length=25)),
                ('feedback', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(default=dict), blank=True, default=list, size=None)),
                ('source_text', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='source_texts.source')),
            ],
        ),
    ]
