# Generated by Django 5.2.5 on 2025-09-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0002_translation_termbase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='body',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
